### PR TITLE
Feature/podaac 5219 cherry pick

### PR DESCRIPTION
**Pull request by yenes56**
Ticket: PODAAC-5219

### Description
NumberUtils.createInteger(String s)

if s has leading zero, then NumberUtils will treat s as Octal format.  this behavior is not what PODAAC expected.
Hence, implemented an util function to remove leading zeros

### Overview of work done

Implemented util function to remove leading zeros
use the util function to remove leading zero before NumberUtils.createInteger
Handle exception and change the MetadataAggregator to throw exception while cycle or pass are missing.

### Overview of verification done

* re-produce the un-wanted behavior in SNDBX
* tested pass value with leading zero and verify pass value through eathdata client search
* tested both cycle and pass values with leading zeros and UMMG are produced as expected
* tested missing pass value and MetadataAggregator will throw exception

#### Tested in SIT:

N/A

## PR checklist:

* [x] Linted
* [x] Unit tests
* [ ] Addressed Snyk vulnerabilities
* [x] Updated changelog
* [ ] Tested in SIT
* [ ] Documentation / User-Guide Updated

_See [Pull Request Review Checklist](https://wiki.earthdata.nasa.gov/display/PCESA/Pull+Request+Review+Checklist) for pointers on reviewing this pull request_

### CODE REVIEW

**Comment by skorper** [comment]
Would downgrading com.amazonaws:aws-java-sdk-s3 fix the snyk issue? Or was that upgraded to due another Snyk issue? 

@jonathansmolenski FYI We're running into issues with this Snyk scan blocking our PR even though there's no upgrade remediation path afaik.

**Comment by skorper** [comment]
@mike-gangl would that be somewhere in the snyk ui?

I can use my admin privs to merge regardless of these checks but i'd prefer to do it the "right" way

**Comment by mike-gangl** [comment]
i think that's the only way and the "right way" given there is no remediation path, and downgrading i think would give issues with existing flaws. @jonathansmolenski can you see what guidance we'd get from ESDIS on this? 

i think my only concern is that if this new vulnerability is critical when a previous vulnerability was less severe, it would make sense to use the less severe vulnerability. This is medium, so i'm not even confident we should be failing on this regardless (high and critical only)

**Comment by skorper** [comment]
@yenes56 Was there a vulnerability on the previous version at all? Or did you just upgrade to the latest version to stay up to date?

**Comment by skorper** [comment]
I'm going to use my admin powers to merge this PR and hopefully we can address some of your points in the future @mike-gangl

**Comment by yenes56** [comment]
@skorper 
     Excuse me for the late response.  Yes, the very same vulnerability on the previous version.  After upgrading the aws libraries, the very same vulnerability stays and root cause is from aws libraries

**Pull request merged**
