### PR TITLE
Feature/podaac 4248 - Only require start, stop, and creation times for ISO files

### PR DESCRIPTION
**Pull request by jocelynmallon**
NOTE: This PR should be merged after #1 to prevent conflicts.

When translating ISO files to UMM-G files, the only essential elements are start, stop, and creation time, everything else is optional.
Moved the parsing of the above three required fields to a new method, which is executed before attempting to parse any optional fields. If any of the required fields is missing, an exception is thrown, and the export is stopped.
Wrapped all optional metadata parsing inside try/catch blocks, where we simply log a warning, instead of stopping the export entirely.
Cleaned up several areas of duplicate code.
Added JavaDoc comments to several methods.
Updated UMMTest for the modified method signatures/parameters.

### CODE REVIEW

**Comment by yenes56** [comment]
merge develop to this branch.   Curtis just finished github action modification and checked into develop

**Comment by jocelynmallon** [comment]
> merge develop to this branch. Curtis just finished github action modification and checked into develop

This PR is built on top or the NSIDC changes in #1 so if we merge develop into this branch instead of merging these changes into dev, we're going to run into conflicts when merging both PR's into develop. But if we don't merge develop into these PR branches, then the merges generate no conflict. I tested both ways with my local copy of the repo.

**Comment by jocelynmallon** [comment]
If our goal is to trigger the GitHub actions to make sure this PR builds properly, I can push a new test branch with both #1 and #2 merged.

**Comment by yenes56** [comment]
Make the following correction.  There probably will be a release based on cumulus 9.x so the following fix is necessary to get things working.   I discover the bug by integration testing. 

image

**Review by ngachung — APPROVED** [review]

**Review by ngachung — APPROVED** [review]

**Pull request merged**
